{
    "exceptions": {
        "cannot_connect": {
            "message": "N\u00e3o \u00e9 poss\u00edvel ligar ao ponto final"
        },
        "invalid_bucket_name": {
            "message": "Nome do balde inv\u00e1lido"
        },
        "invalid_credentials": {
            "message": "N\u00e3o \u00e9 poss\u00edvel aceder ao contentor utilizando a combina\u00e7\u00e3o fornecida de ID da chave de acesso e chave de acesso secreta."
        }
    }
}